version: '3.7'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db_volume:/data

  cache:
    image: redis:7.0-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache_volume:/data

volumes:
  db_volume: {}
  cache_volume: {}
