/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface OrchidzBuildManagerInterface extends utils.Interface {
  functions: {
    "collectionAddressOfCreator(address)": FunctionFragment;
    "createCollectionForCreator(string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "collectionAddressOfCreator"
      | "createCollectionForCreator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "collectionAddressOfCreator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollectionForCreator",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "collectionAddressOfCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollectionForCreator",
    data: BytesLike
  ): Result;

  events: {
    "collectionCreatedForCreator(address,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "collectionCreatedForCreator"
  ): EventFragment;
}

export interface collectionCreatedForCreatorEventObject {
  creator: string;
  collectionAddress: string;
}
export type collectionCreatedForCreatorEvent = TypedEvent<
  [string, string],
  collectionCreatedForCreatorEventObject
>;

export type collectionCreatedForCreatorEventFilter =
  TypedEventFilter<collectionCreatedForCreatorEvent>;

export interface OrchidzBuildManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OrchidzBuildManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    collectionAddressOfCreator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createCollectionForCreator(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  collectionAddressOfCreator(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  createCollectionForCreator(
    _name: PromiseOrValue<string>,
    _symbol: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    collectionAddressOfCreator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    createCollectionForCreator(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "collectionCreatedForCreator(address,address)"(
      creator?: PromiseOrValue<string> | null,
      collectionAddress?: PromiseOrValue<string> | null
    ): collectionCreatedForCreatorEventFilter;
    collectionCreatedForCreator(
      creator?: PromiseOrValue<string> | null,
      collectionAddress?: PromiseOrValue<string> | null
    ): collectionCreatedForCreatorEventFilter;
  };

  estimateGas: {
    collectionAddressOfCreator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createCollectionForCreator(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    collectionAddressOfCreator(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createCollectionForCreator(
      _name: PromiseOrValue<string>,
      _symbol: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
